"""empty message

Revision ID: 01764de42185
Revises: 57ba9dd9e18b
Create Date: 2024-08-01 12:43:37.375644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01764de42185'
down_revision = '57ba9dd9e18b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concert', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concert', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
